import React, { useContext, useReducer } from "react";
import ItemsContext from "../contexts/ItemsContext";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({ cartLength }) {
	const items = useContext(ItemsContext);
	const [cartAdd, dispatch] = useReducer((state, action) => {
		return <h1>{action.type}</h1>;
	}, cartLength);
	return (
		<div className={styles.grid}>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{Object.keys(items).map((item, i) => {
				return (
					<div key={i} className={styles.gridItem}>
						<img src={items[item].image} />
						<h3>{item}</h3>
						<p>{items[item].cost}$</p>
						<button
							onClick={async (e) => {
								await fetch("/cartAdd", {
									headers: {
										Accept: "application/json",
										"Content-Type": "application/json",
									},
									method: "POST",
									body: JSON.stringify({ item }),
								});
							}}
						>
							Add to cart
						</button>
					</div>
				);
			})}
		</div>
	);
}

export function getServerSideProps(context) {
	return {
		props: { cartLength: context.req.cartLength || 0 },
	};
}
